### PR TITLE
make soap client fit for use in Mojo::Test

### PR DESCRIPTION
**Pull request by oetiker**
While writing `Mojo::SOAP::Client` and `Mojolicious::Plugin::SOAP::Server` I found that things fall apart sadly inside `Test::Mojo`. This PR fixes the problem by introducing the ability to supply a Mojo::UserAgent instance from the outside.

I have supplied an appropriate test to handle this case ...

### CODE REVIEW

**Comment by oetiker** [comment]
Ping?

**Comment by markov2** [comment]
Sorry, I have a little too many things to do in December.  Gladly the new year arrived... time to clean-up my inbox.

I had to make a few changes to you patch, so applied it by hand.

**Comment by markov2** [comment]
Released as version 0.05 to CPAN

**Comment by oetiker** [comment]
thanks!

**Pull request closed without merging**
